services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    user: root
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark_apps:/opt/spark/apps
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    user: root
    depends_on:
      - spark-master
    volumes:
      - ./spark_apps:/opt/spark/apps
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=wikiuser
      - POSTGRES_PASSWORD=wikipassword
      - POSTGRES_DB=wikidb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@wikipulse.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8889:80"

  superset:
    image: amancevice/superset
    container_name: superset
    depends_on:
      - postgres
    ports:
      - "8888:8088"
    environment:
      - SUPERSET_SECRET_KEY=m6ENHUA0mwfAtwFdkorx65ywEIDI_JPbJpQnfwnDwcg
      - SUPERSET_CONFIG_PATH=/etc/superset/superset_config.py
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py

volumes:
  postgres_data: